typography_spectrum: 0.9795373152010143
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.9317744930740446
  lightness: 0.9508691607043147
  saturation: 0.382921208627522
  rhythmicContrast: 0.2967894822359085
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4994452125392854
analytics:
  google: null
  facebook: null
  twitter: null
author:
  url: www.lamaphotography.com
name: Lama Photography
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Ontario
    id: 34a13927-0064-4ac1-bfb3-468b4026d854
    type: content
favicon: null
title: Travel & Landscape Photography
description: Travel & Landscape Photography
purpose: []
