layout_spectrum: 0.4994452125392854
typography_spectrum: 0.9795373152010143
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.9317744930740446
  lightness: 0.9508691607043147
  saturation: 0.382921208627522
  rhythmicContrast: 0.2967894822359085
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Lama Photography
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Lama Photography
purpose: []
