typography_spectrum: 0.12091683084145188
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.4977497023064643
  lightness: 0.2677782087121159
  saturation: 0.21856980002485216
  rhythmicContrast: 0.9475325711537153
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3498166592326015
analytics:
  google: null
  facebook: null
  twitter: null
name: Lama Photography
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Lama Photography
purpose: []
